language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

before_install:
  - pip install --user codecov

before_script:
    - composer self-update
    - composer install
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit -c phpunit.xml.dist

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
    - CODECLIMATE_REPO_TOKEN=7f31866ce1a6e1672b23a53ed767283332b189f64dff7fe39bce8ddca2eb91fa ./vendor/bin/test-reporter

after_success:
  - codecov

git:
  depth: 5
